services:
  open-ip-kvm:
    container_name: open-ip-kvm
    image: hammusings/open-ip-kvm:latest
    ports:
      - 8000:8000
      - 8010:8010
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
networks: {}
